# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'pes'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: 关于我们
    submenu:
      - name: 愿景与目标
        link: /projects/microbam
      - name: FAQs
        link: /projects/ourlegacy
  - name: 文献译介
    link: /
  - name: 原创成果
    link: /tags
  - name: 资料推荐
    link: /about
  - name: 联系我们
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/alainpham
      - name: QQ
        icon: linkedin-square
        link: http://www.linkedin.com/in/alainpham
      - name: 民主计划经济评论
        icon: twitter
        link: https://twitter.com/koint
    
